extends: default

ignore: |
  gitops/platform/charts/namespace-config/templates/
  gitops/workloads/charts/jenkins-storage/templates/
  .terraform/

rules:
  document-start: disable
  indentation:
    indent-sequences: whatever
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
