apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pvName }}
spec:
  capacity:
    storage: {{ .Values.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ printf "%s::%s" .Values.fileSystemId .Values.accessPointId | quote }}
