apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.claimName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassName }}
  volumeName: {{ .Values.pvName }}
  resources:
    requests:
      storage: {{ .Values.capacity }}
